// constants

if (!global.ME)
{
    var structNames = Object.keys(Game.structures);
    if (structNames.length > 0)
    	global.ME = Game.structures[structNames[0]].owner.username;
    else
        global.ME = "";
};

global.TERMINAL_ACTION_HOLD          = "HOLD";
global.TERMINAL_ACTION_BUY_NOW       = "BUY_NOW";
global.TERMINAL_ACTION_BUY           = "BUY";
global.TERMINAL_ACTION_SELL          = "SELL";
global.TERMINAL_ACTION_DUMP          = "DUMP";
global.TERMINAL_ACTION_DISTRIBUTE    = "DISTRIBUTE";

global.RESOURCE_THORIUM = global.RESOURCE_THORIUM || 'T';

module.exports =
{
    TRY_CATCH: 1,

    SEASON_FOUR_ACTIVE: false && Game.shard.name == 'shardSeason',
    SEASON_FIVE_ACTIVE: false && Game.shard.name == 'shardSeason',

    CPU_BUCKET_SIZE: 10000,

    MARKET_EXISTS: false,

    AUTO_CLAIM: true,
    AUTO_CLAIM_REALLY: true,
    AUTO_UNCLAIM: true,
    AUTO_UNCLAIM_REALLY: true,

    AUTO_ATTACK: true,

    USE_FACTORY: false,

    USE_POWER: false,

    MONITOR_CREEP: 'bk1ca',

    BUCKET_BRIGADE: 0,

    SPENDABLE_MULTIPLIER: 0.75,

    SHARD_ROOM_COUNT_BALANCING: false,

    MAX_POSSIBLE_ENERGY_CAPACITY: (EXTENSION_ENERGY_CAPACITY[8] * CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][8]) + (SPAWN_ENERGY_CAPACITY * CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][8]),

    MIN_RAMPART_PERCENT:        0.2,

    MIN_RAMPART_HITS:       1000000,
    DESIRED_RAMPART_HITS:   5000000,

    AGGRESSION_LEVEL_ALLY     : 1,
    AGGRESSION_LEVEL_FRIENDLY : 2,
    AGGRESSION_LEVEL_NEUTRAL  : 3,
    AGGRESSION_LEVEL_HOSTILE  : 4,
    AGGRESSION_LEVEL_ENEMY    : 5,

    ALLOW_BUY_NOW: 0,
    ALLOW_BUY: 0,
    ALLOW_DUMP: 1,
    ALLOW_SELL: 0,

    MIN_CREDITS_FOR_BUY_NOW:    0,//50000000,
    MIN_CREDITS_FOR_BUY:        0,//25000000,

    MAX_CREDITS_FOR_SELL:       500000,

    RESOURCE_LEVEL_NONE     : 0,
    RESOURCE_LEVEL_CRITICAL : 1,
    RESOURCE_LEVEL_LOW      : 2,
    RESOURCE_LEVEL_MODERATE : 3,
    RESOURCE_LEVEL_NORMAL   : 4,
    RESOURCE_LEVEL_HIGH     : 5,
    RESOURCE_LEVEL_EXCESS   : 6,

    DUMP_RESOURCE_LEVEL: 6,

    RESOURCE_LEVEL_NAMES:
    [
        'NONE',
        'CRITICAL',
        'LOW',
        'MODERATE',
        'NORMAL',
        'HIGH',
        'EXCESS'
    ],

    BUY_TO_THRESHOLD: 0.5,

    LOW_RESOURCE_THRESHOLD      : 0.1,
    MODERATE_RESOURCE_THRESHOLD : 0.3,
    NORMAL_RESOURCE_THRESHOLD   : 0.75,
    HIGH_RESOURCE_THRESHOLD     : 1.5,
    EXCESS_RESOURCE_THRESHOLD   : 2.0,

    MIN_RESOURCE_PERCENT_DIFFERENCE_TO_BALANCE: .25,

    MIN_RESOURCE_AMOUNT_TO_BALANCE: 1000,

    RESOURCES_ALL_REVERSED: RESOURCES_ALL.slice().reverse(),

    FACTORY_MIN_INPUT: 500,

    FACTORY_INPUT_RESOURCES: _.unique(_.reduce(COMMODITIES, function(result, c) { return result.concat(Object.keys(c.components)) }, [])),

    PART_COLORS:
    {
        [MOVE] : '#a9b7c6',
        [WORK] : '#ffe56d',

        [CARRY]: '#777777',

        [CLAIM]: '#b99cfb'
    },

    BODYPARTS:
    [
        "move",
        "work",
        "attack",
        "carry",
        "heal",
        "ranged_attack",
        "tough",
        "claim"
    ],

    BODYPART_INDEX:
    {
        "move"          : 0,
        "work"          : 1,
        "attack"        : 2,
        "carry"         : 3,
        "heal"          : 4,
        "ranged_attack" : 5,
        "tough"         : 6,
        "claim"         : 7
    },

    RESOURCES_MINERAL:
    [
        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST
    ],

    BASE_MINERAL_PRIORITY:
    {
        [RESOURCE_HYDROGEN]    : 15 / 7,
        [RESOURCE_OXYGEN]      : 17 / 7,
        [RESOURCE_UTRIUM]      :  9 / 7,
        [RESOURCE_KEANIUM]     : 13 / 7,
        [RESOURCE_LEMERGIUM]   : 19 / 7,
        [RESOURCE_ZYNTHIUM]    : 11 / 7,
        [RESOURCE_CATALYST]    :  7 / 7,
    },

    BASE_MINERAL_VALUE:
    {
        [RESOURCE_HYDROGEN]    : 38 / 38,
        [RESOURCE_OXYGEN]      : 37 / 38,
        [RESOURCE_UTRIUM]      :  9 / 38,
        [RESOURCE_KEANIUM]     : 11 / 38,
        [RESOURCE_LEMERGIUM]   : 12 / 38,
        [RESOURCE_ZYNTHIUM]    : 11 / 38,
        [RESOURCE_CATALYST]    : 25 / 38,
    },

    RESOURCES_FACTORY:
    [
        //RESOURCE_BATTERY
    ],

    RESOURCES_TO_TRADE:
    [
        RESOURCE_ENERGY,

        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST
    ],

    RESOURCES_TO_BUY_NOW:
    [
        // RESOURCE_ENERGY,

        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST
    ],

    RESOURCES_TO_BUY:
    [
        //RESOURCE_ENERGY,

        //RESOURCE_POWER,

        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST
    ],

    // RESOURCES_TO_SELL: RESOURCES_ALL.slice().reverse(),
    // RESOURCES_TO_DUMP: RESOURCES_ALL.slice().reverse(),

    RESOURCES_TO_SELL:
    [
        // RESOURCE_HYDROGEN,
        // RESOURCE_OXYGEN,
        // RESOURCE_UTRIUM,
        // RESOURCE_KEANIUM,
        // RESOURCE_LEMERGIUM,
        // RESOURCE_ZYNTHIUM,
        // RESOURCE_CATALYST,

        RESOURCE_REDUCTANT,
        RESOURCE_OXIDANT,
        RESOURCE_UTRIUM_BAR,
        RESOURCE_KEANIUM_BAR,
        RESOURCE_LEMERGIUM_BAR,
        RESOURCE_ZYNTHIUM_BAR,
        RESOURCE_PURIFIER,

        RESOURCE_GHODIUM_MELT,

        RESOURCE_BATTERY
    ],

    RESOURCES_TO_DUMP:
    [
        RESOURCE_ENERGY,

        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST,

        RESOURCE_REDUCTANT,
        RESOURCE_OXIDANT,
        RESOURCE_UTRIUM_BAR,
        RESOURCE_KEANIUM_BAR,
        RESOURCE_LEMERGIUM_BAR,
        RESOURCE_ZYNTHIUM_BAR,
        RESOURCE_PURIFIER,

        RESOURCE_GHODIUM_MELT,

        RESOURCE_BATTERY
    ],

    RESOURCES_TO_COMPRESS:
    [
        RESOURCE_ENERGY,

        RESOURCE_HYDROGEN,
        RESOURCE_OXYGEN,
        RESOURCE_UTRIUM,
        RESOURCE_KEANIUM,
        RESOURCE_LEMERGIUM,
        RESOURCE_ZYNTHIUM,
        RESOURCE_CATALYST,

        RESOURCE_GHODIUM
    ],

    RESOURCES_TO_DECOMPRESS:
    [
        RESOURCE_BATTERY,

        RESOURCE_REDUCTANT,
        RESOURCE_OXIDANT,
        RESOURCE_UTRIUM_BAR,
        RESOURCE_KEANIUM_BAR,
        RESOURCE_LEMERGIUM_BAR,
        RESOURCE_ZYNTHIUM_BAR,
        RESOURCE_PURIFIER,

        RESOURCE_GHODIUM_MELT
    ],

    RESOURCE_COMPRESSES_TO:
    {
        [RESOURCE_ENERGY]      : RESOURCE_BATTERY,

        [RESOURCE_HYDROGEN]    : RESOURCE_REDUCTANT,
        [RESOURCE_OXYGEN]      : RESOURCE_OXIDANT,
        [RESOURCE_UTRIUM]      : RESOURCE_UTRIUM_BAR,
        [RESOURCE_KEANIUM]     : RESOURCE_KEANIUM_BAR,
        [RESOURCE_LEMERGIUM]   : RESOURCE_LEMERGIUM_BAR,
        [RESOURCE_ZYNTHIUM]    : RESOURCE_ZYNTHIUM_BAR,
        [RESOURCE_CATALYST]    : RESOURCE_PURIFIER,

        [RESOURCE_GHODIUM]     : RESOURCE_GHODIUM_MELT
    },

    RESOURCE_DECOMPRESSES_TO:
    {
        [RESOURCE_BATTERY]         : RESOURCE_ENERGY,

        [RESOURCE_REDUCTANT]       : RESOURCE_HYDROGEN,
        [RESOURCE_OXIDANT]         : RESOURCE_OXYGEN,
        [RESOURCE_UTRIUM_BAR]      : RESOURCE_UTRIUM,
        [RESOURCE_KEANIUM_BAR]     : RESOURCE_KEANIUM,
        [RESOURCE_LEMERGIUM_BAR]   : RESOURCE_LEMERGIUM,
        [RESOURCE_ZYNTHIUM_BAR]    : RESOURCE_ZYNTHIUM,
        [RESOURCE_PURIFIER]        : RESOURCE_CATALYST,

        [RESOURCE_GHODIUM_MELT]    : RESOURCE_GHODIUM
    },

    DESIRED_RESOURCE_AMOUNT:
    {
        [RESOURCE_ENERGY] : 150000,
        [RESOURCE_POWER]  :  10000,

        [RESOURCE_HYDROGEN]  : 10000,
        [RESOURCE_OXYGEN]    : 10000,
        [RESOURCE_UTRIUM]    : 10000,
        [RESOURCE_KEANIUM]   : 10000,
        [RESOURCE_LEMERGIUM] : 10000,
        [RESOURCE_ZYNTHIUM]  : 10000,
        [RESOURCE_CATALYST]  : 10000,

        [RESOURCE_GHODIUM]   : 10000,

        [RESOURCE_HYDROXIDE]         :  5000,
        [RESOURCE_ZYNTHIUM_KEANITE]  :  5000,
        [RESOURCE_UTRIUM_LEMERGITE]  :  5000,

        [RESOURCE_UTRIUM_HYDRIDE]    : 5000,
        [RESOURCE_UTRIUM_OXIDE]      : 5000,
        [RESOURCE_KEANIUM_HYDRIDE]   : 5000,
        [RESOURCE_KEANIUM_OXIDE]     : 5000,
        [RESOURCE_LEMERGIUM_HYDRIDE] : 5000,
        [RESOURCE_LEMERGIUM_OXIDE]   : 10000,
        [RESOURCE_ZYNTHIUM_HYDRIDE]  : 5000,
        [RESOURCE_ZYNTHIUM_OXIDE]    : 5000,
        [RESOURCE_GHODIUM_HYDRIDE]   : 5000,
        [RESOURCE_GHODIUM_OXIDE]     : 5000,

        [RESOURCE_UTRIUM_ACID]          : 10000,
        [RESOURCE_UTRIUM_ALKALIDE]      : 10000,
        [RESOURCE_KEANIUM_ACID]         : 10000,
        [RESOURCE_KEANIUM_ALKALIDE]     : 10000,
        [RESOURCE_LEMERGIUM_ACID]       : 10000,
        [RESOURCE_LEMERGIUM_ALKALIDE]   : 20000,
        [RESOURCE_ZYNTHIUM_ACID]        : 10000,
        [RESOURCE_ZYNTHIUM_ALKALIDE]    : 10000,
        [RESOURCE_GHODIUM_ACID]         : 10000,
        [RESOURCE_GHODIUM_ALKALIDE]     : 10000,

        [RESOURCE_CATALYZED_UTRIUM_ACID]        : 20000,
        [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]    : 20000,
        [RESOURCE_CATALYZED_KEANIUM_ACID]       : 20000,
        [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]   : 20000,
        [RESOURCE_CATALYZED_LEMERGIUM_ACID]     : 20000,
        [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE] : 20000,
        [RESOURCE_CATALYZED_ZYNTHIUM_ACID]      : 20000,
        [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]  : 20000,
        [RESOURCE_CATALYZED_GHODIUM_ACID]       : 20000,
        [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]   : 20000,

        [RESOURCE_OPS]     : 10000,

        [RESOURCE_SILICON]  : 10000,
        [RESOURCE_METAL]    : 10000,
        [RESOURCE_BIOMASS]  : 10000,
        [RESOURCE_MIST]     : 10000,

        [RESOURCE_BATTERY]      : 10000,
        [RESOURCE_REDUCTANT]    : 10000,
        [RESOURCE_OXIDANT]      : 10000,
        [RESOURCE_UTRIUM_BAR]   : 10000,
        [RESOURCE_KEANIUM_BAR]  : 10000,
        [RESOURCE_LEMERGIUM_BAR]: 10000,
        [RESOURCE_ZYNTHIUM_BAR] : 10000,
        [RESOURCE_PURIFIER]     : 10000,

        [RESOURCE_GHODIUM_MELT] : 10000,

        [RESOURCE_COMPOSITE]    : 2000,
        [RESOURCE_CRYSTAL]      : 2000,
        [RESOURCE_LIQUID]       : 2000,

        [RESOURCE_WIRE]         : 1000,
        [RESOURCE_SWITCH]       : 1000,
        [RESOURCE_TRANSISTOR]   : 1000,
        [RESOURCE_MICROCHIP]    : 1000,
        [RESOURCE_CIRCUIT]      : 1000,
        [RESOURCE_DEVICE]       : 1000,

        [RESOURCE_CELL]         : 1000,
        [RESOURCE_PHLEGM]       : 1000,
        [RESOURCE_TISSUE]       : 1000,
        [RESOURCE_MUSCLE]       : 1000,
        [RESOURCE_ORGANOID]     : 1000,
        [RESOURCE_ORGANISM]     : 1000,

        [RESOURCE_ALLOY]        : 1000,
        [RESOURCE_TUBE]         : 1000,
        [RESOURCE_FIXTURES]     : 1000,
        [RESOURCE_FRAME]        : 1000,
        [RESOURCE_HYDRAULICS]   : 1000,
        [RESOURCE_MACHINE]      : 1000,

        [RESOURCE_CONDENSATE]   : 1000,
        [RESOURCE_CONCENTRATE]  : 1000,
        [RESOURCE_EXTRACT]      : 1000,
        [RESOURCE_SPIRIT]       : 1000,
        [RESOURCE_EMANATION]    : 1000,
        [RESOURCE_ESSENCE]      : 1000
    },

    PRIORITY_COMPOUNDS:
    [
        { r: [RESOURCE_KEANIUM_OXIDE        ], a: 2000 },
        { r: [RESOURCE_LEMERGIUM_OXIDE      ], a: 2000 },
        { r: [RESOURCE_ZYNTHIUM_OXIDE       ], a: 2000 },

        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 1000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 1000 },

        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 2000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 2000 },

        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 3000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 3000 },

        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 6000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 6000 },

        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 10000 },
        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 10000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE , RESOURCE_LEMERGIUM_ALKALIDE   , RESOURCE_LEMERGIUM_OXIDE      ], a: 3000 },
        { r: [RESOURCE_CATALYZED_GHODIUM_ALKALIDE   , RESOURCE_GHODIUM_ALKALIDE     , RESOURCE_GHODIUM_OXIDE        ], a: 3000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ACID      , RESOURCE_ZYNTHIUM_ACID        , RESOURCE_ZYNTHIUM_HYDRIDE     ], a: 3000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE  , RESOURCE_ZYNTHIUM_ALKALIDE    , RESOURCE_ZYNTHIUM_OXIDE       ], a: 3000 },
        // { r: [RESOURCE_CATALYZED_KEANIUM_ACID       , RESOURCE_KEANIUM_ACID         , RESOURCE_KEANIUM_HYDRIDE      ], a: 3000 },
        // { r: [RESOURCE_CATALYZED_UTRIUM_ACID        , RESOURCE_UTRIUM_ACID          , RESOURCE_UTRIUM_HYDRIDE       ], a: 3000 },
        // { r: [RESOURCE_CATALYZED_UTRIUM_ALKALIDE    , RESOURCE_UTRIUM_ALKALIDE      , RESOURCE_UTRIUM_OXIDE         ], a: 3000 },
        // { r: [RESOURCE_CATALYZED_GHODIUM_ACID       , RESOURCE_GHODIUM_ACID         , RESOURCE_GHODIUM_HYDRIDE      ], a: 3000 },


        { r: [RESOURCE_HYDROXIDE]         , a: 1000 },

        { r: [RESOURCE_GHODIUM]           , a: 1000 },
        { r: [RESOURCE_ZYNTHIUM_KEANITE]  , a: 1000 },
        { r: [RESOURCE_UTRIUM_LEMERGITE]  , a: 1000 },

        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 6000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE , RESOURCE_LEMERGIUM_ALKALIDE   , RESOURCE_LEMERGIUM_OXIDE      ], a: 6000 },
        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 6000 },
        { r: [RESOURCE_CATALYZED_GHODIUM_ALKALIDE   , RESOURCE_GHODIUM_ALKALIDE     , RESOURCE_GHODIUM_OXIDE        ], a: 6000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ACID      , RESOURCE_ZYNTHIUM_ACID        , RESOURCE_ZYNTHIUM_HYDRIDE     ], a: 6000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE  , RESOURCE_ZYNTHIUM_ALKALIDE    , RESOURCE_ZYNTHIUM_OXIDE       ], a: 6000 },
        // { r: [RESOURCE_CATALYZED_KEANIUM_ACID       , RESOURCE_KEANIUM_ACID         , RESOURCE_KEANIUM_HYDRIDE      ], a: 6000 },
        // { r: [RESOURCE_CATALYZED_UTRIUM_ACID        , RESOURCE_UTRIUM_ACID          , RESOURCE_UTRIUM_HYDRIDE       ], a: 6000 },

        { r: [RESOURCE_CATALYZED_LEMERGIUM_ACID     , RESOURCE_LEMERGIUM_ACID       , RESOURCE_LEMERGIUM_HYDRIDE    ], a: 10000 },
        { r: [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE , RESOURCE_LEMERGIUM_ALKALIDE   , RESOURCE_LEMERGIUM_OXIDE      ], a: 10000 },
        { r: [RESOURCE_CATALYZED_KEANIUM_ALKALIDE   , RESOURCE_KEANIUM_ALKALIDE     , RESOURCE_KEANIUM_OXIDE        ], a: 10000 },
        { r: [RESOURCE_CATALYZED_GHODIUM_ALKALIDE   , RESOURCE_GHODIUM_ALKALIDE     , RESOURCE_GHODIUM_OXIDE        ], a: 10000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ACID      , RESOURCE_ZYNTHIUM_ACID        , RESOURCE_ZYNTHIUM_HYDRIDE     ], a: 10000 },
        { r: [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE  , RESOURCE_ZYNTHIUM_ALKALIDE    , RESOURCE_ZYNTHIUM_OXIDE       ], a: 10000 },
        // { r: [RESOURCE_CATALYZED_KEANIUM_ACID       , RESOURCE_KEANIUM_ACID         , RESOURCE_KEANIUM_HYDRIDE      ], a: 10000 },
        // { r: [RESOURCE_CATALYZED_UTRIUM_ACID        , RESOURCE_UTRIUM_ACID          , RESOURCE_UTRIUM_HYDRIDE       ], a: 10000 },
    ],

    COMPOUNDS_TO_PRODUCE:
    [
        RESOURCE_GHODIUM,

        RESOURCE_HYDROXIDE,
        RESOURCE_ZYNTHIUM_KEANITE,
        RESOURCE_UTRIUM_LEMERGITE,

        RESOURCE_UTRIUM_HYDRIDE,
        RESOURCE_UTRIUM_OXIDE,
        RESOURCE_KEANIUM_HYDRIDE,
        RESOURCE_KEANIUM_OXIDE,
        RESOURCE_LEMERGIUM_HYDRIDE,
        RESOURCE_LEMERGIUM_OXIDE,
        RESOURCE_ZYNTHIUM_HYDRIDE,
        RESOURCE_ZYNTHIUM_OXIDE,
        RESOURCE_GHODIUM_HYDRIDE,
        RESOURCE_GHODIUM_OXIDE,

        RESOURCE_UTRIUM_ACID,
        RESOURCE_UTRIUM_ALKALIDE,
        RESOURCE_KEANIUM_ACID,
        RESOURCE_KEANIUM_ALKALIDE,
        RESOURCE_LEMERGIUM_ACID,
        RESOURCE_LEMERGIUM_ALKALIDE,
        RESOURCE_ZYNTHIUM_ACID,
        RESOURCE_ZYNTHIUM_ALKALIDE,
        RESOURCE_GHODIUM_ACID,
        RESOURCE_GHODIUM_ALKALIDE,

        RESOURCE_CATALYZED_UTRIUM_ACID,
        RESOURCE_CATALYZED_UTRIUM_ALKALIDE,
        RESOURCE_CATALYZED_KEANIUM_ACID,
        RESOURCE_CATALYZED_KEANIUM_ALKALIDE,
        RESOURCE_CATALYZED_LEMERGIUM_ACID,
        RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE,
        RESOURCE_CATALYZED_ZYNTHIUM_ACID,
        RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE,
        RESOURCE_CATALYZED_GHODIUM_ACID,
        RESOURCE_CATALYZED_GHODIUM_ALKALIDE,
    ],

    /**
     * Posted 13 March 2018 by @shibdib
     * Boost Components
     */
    BOOST_COMPONENTS:
    {
        //Tier 3
        [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_ALKALIDE, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_GHODIUM_ACID]: [RESOURCE_GHODIUM_ACID, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_ACID, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_ALKALIDE, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_ALKALIDE, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_ACID, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_ALKALIDE, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_KEANIUM_ACID]: [RESOURCE_KEANIUM_ACID, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_UTRIUM_ACID]: [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
        [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_ALKALIDE, RESOURCE_CATALYST],
        //Tier 2
        [RESOURCE_GHODIUM_ACID]: [RESOURCE_GHODIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_OXIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_OXIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_OXIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_OXIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_KEANIUM_ACID]: [RESOURCE_KEANIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_UTRIUM_ACID]: [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        [RESOURCE_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_OXIDE, RESOURCE_HYDROXIDE],
        //Tier 1
        [RESOURCE_GHODIUM_HYDRIDE]: [RESOURCE_GHODIUM, RESOURCE_HYDROGEN],
        [RESOURCE_GHODIUM_OXIDE]: [RESOURCE_GHODIUM, RESOURCE_OXYGEN],
        [RESOURCE_ZYNTHIUM_HYDRIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_HYDROGEN],
        [RESOURCE_ZYNTHIUM_OXIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_OXYGEN],
        [RESOURCE_LEMERGIUM_OXIDE]: [RESOURCE_LEMERGIUM, RESOURCE_OXYGEN],
        [RESOURCE_LEMERGIUM_HYDRIDE]: [RESOURCE_LEMERGIUM, RESOURCE_HYDROGEN],
        [RESOURCE_KEANIUM_OXIDE]: [RESOURCE_KEANIUM, RESOURCE_OXYGEN],
        [RESOURCE_KEANIUM_HYDRIDE]: [RESOURCE_KEANIUM, RESOURCE_HYDROGEN],
        [RESOURCE_UTRIUM_HYDRIDE]: [RESOURCE_UTRIUM, RESOURCE_HYDROGEN],
        [RESOURCE_UTRIUM_OXIDE]: [RESOURCE_UTRIUM, RESOURCE_OXYGEN],
        //Base
        [RESOURCE_GHODIUM]: [RESOURCE_ZYNTHIUM_KEANITE, RESOURCE_UTRIUM_LEMERGITE],
        [RESOURCE_HYDROXIDE]: [RESOURCE_OXYGEN, RESOURCE_HYDROGEN],
        [RESOURCE_ZYNTHIUM_KEANITE]: [RESOURCE_ZYNTHIUM, RESOURCE_KEANIUM],
        [RESOURCE_UTRIUM_LEMERGITE]: [RESOURCE_UTRIUM, RESOURCE_LEMERGIUM]
    },

    BOOST_PARTS:
    {
        [RESOURCE_UTRIUM_HYDRIDE]    : ATTACK,
        [RESOURCE_UTRIUM_OXIDE]      : WORK,
        [RESOURCE_KEANIUM_HYDRIDE]   : CARRY,
        [RESOURCE_KEANIUM_OXIDE]     : RANGED_ATTACK,
        [RESOURCE_LEMERGIUM_HYDRIDE] : WORK,
        [RESOURCE_LEMERGIUM_OXIDE]   : HEAL,
        [RESOURCE_ZYNTHIUM_HYDRIDE]  : WORK,
        [RESOURCE_ZYNTHIUM_OXIDE]    : MOVE,
        [RESOURCE_GHODIUM_HYDRIDE]   : WORK,
        [RESOURCE_GHODIUM_OXIDE]     : TOUGH,

        [RESOURCE_UTRIUM_ACID]          : ATTACK,
        [RESOURCE_UTRIUM_ALKALIDE]      : WORK,
        [RESOURCE_KEANIUM_ACID]         : CARRY,
        [RESOURCE_KEANIUM_ALKALIDE]     : RANGED_ATTACK,
        [RESOURCE_LEMERGIUM_ACID]       : WORK,
        [RESOURCE_LEMERGIUM_ALKALIDE]   : HEAL,
        [RESOURCE_ZYNTHIUM_ACID]        : WORK,
        [RESOURCE_ZYNTHIUM_ALKALIDE]    : MOVE,
        [RESOURCE_GHODIUM_ACID]         : WORK,
        [RESOURCE_GHODIUM_ALKALIDE]     : TOUGH,

        [RESOURCE_CATALYZED_UTRIUM_ACID]        : ATTACK,
        [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]    : WORK,
        [RESOURCE_CATALYZED_KEANIUM_ACID]       : CARRY,
        [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]   : RANGED_ATTACK,
        [RESOURCE_CATALYZED_LEMERGIUM_ACID]     : WORK,
        [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE] : HEAL,
        [RESOURCE_CATALYZED_ZYNTHIUM_ACID]      : WORK,
        [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]  : MOVE,
        [RESOURCE_CATALYZED_GHODIUM_ACID]       : WORK,
        [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]   : TOUGH
    }
};
